[package]
name = "tetris"
version = "0.1.0"
authors = ["Richard Chen <richard.rl.chen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm="0.19.0"
rand="0.8.3"
